FROM python:3.8-slim
LABEL maintainer="Daniel Du, danghoangnhan.1@gmail.com"

RUN apt-get update -y
RUN apt-get install -y build-essential
RUN pip install --upgrade pip

COPY . /app
WORKDIR /app

RUN pip install -r requirements.txt

ENTRYPOINT ["python"]
CMD ["app.py"]